/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Achievement Gotten!": "成就达成！",'Achievement': '成就',
    'Achievements': '成就',
    'Buy': '购买',
    'Dashboard': '仪表盘',
    'Generator': '发生器',
    'Matter': '物质',
    'Number': '数字',
    'Price': '价格',
    'Options': '选项',
    'Statistics': '统计',
    'Total H': 'H 总量',
    'Upgrades': '升级',
    'Warning': '警告',
    'Hydrogen': '氢',
    'NaN ': '未知',
    'Nucleogenesis v2.': '核起源 v2.',
    'This is an early beta version under heavy development. Expect unbalanced gameplay, bugs, save wipes and broken features.': '这是一个早期的测试版，正在进行大量的开发。可能有不平衡的游戏玩法，bug，存档丢失和不完整的功能。',
    'Activate': '激活',
    'Faster ticks: spend your offline gains to accelerate game speed.': '更快的节奏:利用你的离线收益来加快游戏速度。',
    'Gather Hydrogen': '收集氢',
    'Export Save': '导出存档',
    'Exotic Hydrogen': '外来氢',
    'All time': '所有时间',
    'Buy all': '全部购买',
    'Changelog': '更新日志',
    'Exotic run': '外来运行',
    'Dark run': '暗运行',
    'Hide bought upgrades': '隐藏已购买升级',
    'Hide completed achivements': '隐藏已完成成就',
    'Import Save': '导入存档',
    'Name': '名称',
    'Number Format': '数字格式',
    'Scientific': '科学计数法',
    'Sort by': '排序方式',
    'Standard': '标准',
    'Unlock all Hydrogen isotopes': '解锁所有氢同位素',
    'Unlock all isotopes': '解锁所有同位素',
    'Unlock the shortest lived isotope': '解锁最短寿命的同位素',
    'Erase save': '删除存档',
    'Hybrid': '混合',
    'Engineering': '工程符号',
    'Global': '全局',
    'Gather exotic Hydrogen': '收集外来氢',
    'Hydrogen isotopes': '氢同位素',
    'Isotopes': '同位素',
    'Most unstable': '最不稳定',
    'Exotic matter': '外来物质',
    'Periodic Table': '周期表',
    'Reactions': '反应',
    'Redox': '氧化还原',
    'Redoxes': '氧化还原',
    'Dark matter': '暗物质',
    'Abundance': '丰富',
    'Purchased': '已购买',
    'Available': '可用',
    'Unavailable': '不可用',
    'Success': '成功率',
    'Electronegativity': '电负性',
    'Automation I: Automatically buy upgrades': '自动化 I:自动购买升级',
    'Automation II: Automatically buy generators': '自动化II:自动购买发生器',
    'Automation III: Automatically generate exotic matter': '自动化III:自动生成外来物质',
//    'eV': '电伏',
    'dark_matter' :'暗物质',
    'Prestige': '声望',
    'Prestige now to obtain': '现在即将获得的声望',
    'You produced': '你生产的',
    'Sacrifice your progress to obtain dark matter. Dark matter boosts your global production 10% and unlocks new upgrades.': '牺牲你的游戏进度来获得暗物质。 暗物质使您的全局产量提高10％并解锁新的升级。',
    'Extra element slot I: Unlocks another slot to produce matter': '额外元素插槽I：解锁另一个插槽以产生物质',
    'Extra element slot II: Unlocks another slot to produce matter': '额外元素插槽II：解锁另一个插槽以产生物质',
    'Extra element slot III: Unlocks another slot to produce matter': '额外元素插槽III：解锁另一个插槽以产生物质',
    'Most charged': '最多充电',
    'Radioisotopes': '放射性同位素',
    'Unlock all elements': '解锁所有元素',
    'Unlock all ions': '解锁所有离子',
    'Unlock all meta resources': '解锁所有元资源',
    'Unlock all radioactive isotopes': '解锁所有放射性同位素',
    'Unlock an extremely charged ion': '解锁极电荷的离子',
    'Unlock every single resource': '解锁每个独立资源',
    'Hide': '隐藏',
    'Buy new elements to unlock generators and upgrades. Success rate is proportional to each element abundance. Accumulate resources or spend more ∅ to increase the chance of success. All used ∅ will be consumed on purchase.': '购买新元素以解锁发生器和升级。 成功率与每个元素丰度成正比。 积累资源或花费更多∅来增加成功的机会。 所有用过的∅都会在购买时消耗掉。',
    'Chance': '几率',
    'Buy amount': '购买数量',
    'Color': '颜色',
    'Hide': '隐藏',
    'Legend': '传奇',
    'Synthetic': '合成物质',
    'State': '状态',
    'Bandwidth': '带宽',
    'Adjust level': '调整等级',
    'Adjust amount': '调整数量',
    'level': '等级',
    'Select an element for slot': '选择插槽元素',
    'Toggle all': '全部切换',
    'Active': '激活',
    'Add': '添加',
    'Reaction': '反应',
    'Remove': '移除',
    'All resources': '全部资源',
    'Elements': '元素',
    'Misc': '杂项',
    'Ions': '离子',
    'Hydrogen molecules': '氢分子',
    'Largest molecule': '最大的分子',
    'Molecules': '分子',
    'Unlock a gargantuan molecule': '解锁一个庞大的分子',
    'Unlock all Hydrogen molecules': '解锁所有氢分子',
    'Unlock all molecules': '解锁所有分子',
    'Ions charge bonus: Ions produce +10% exotic matter per charge': '离子充电加成:离子每次充电产生+10%的外来物质',
    'Total boost': '总提升',
    'Subatomic particles passively increase your exotic production.': '亚原子粒子被动地增加外来产量。',
    'Sacrifice your progress to obtain exotic matter. Exotic matter boosts your production for the element by 1% and unlocks new upgrades.': '牺牲你的游戏进度来获得外来物质。外来物质可以使你的元素产量提高1%，并开启新的升级。',
    'Radioactive bonus: Radioactive isotopes produce +10% exotic matter per order of magnitude of its half life': '放射性奖励:放射性同位素在其半衰期的每个数量级上产生+10%的外来物质',
    'Molecules size bonus: Molecules produce +5% exotic matter per atom': '分子大小奖励:每个原子产生+5%的外来物质',
    'From': '从',
    'To': '到',
    'IV multiplier 1: Tier IV production': 'IV 级加成 1：第 IV 层产量',
    'Unlock all Helium ions': '解锁所有氦离子',
    'Unlock all Helium isotopes': '解锁所有氦同位素',
    'Misc.': '杂项',
    'Exotic Helium': '外来氦',
    'Gather exotic Helium': '收集外来氦',
    'Gather Helium': '收集氦',
    'Helium ions': '氦离子',
    'Helium isotopes': '氦同位素',
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",//元素
    'Barium': '钡',
    'Berkelium': '锫',
    'Beryllium': '铍',
    'Flerovium': '鈇',
    'Fluorine': '氟',
    'Actinium': '锕',
    'Aluminium': '铝',
    'Americium': '镅',
    'Antimony': '锑',
    'Argon': '氩',
    'Arsenic': '砷',
    'Astatine': '砹',
    'Bismuth': '铋',
    'Bohrium': '𬭛',
    'Boron': '硼',
    'Bromine': '溴',
    'Cadmium': '镉',
    'Caesium': '铯',
    'Calcium': '钙',
    'Californium': '锎',
    'Carbon': '碳',
    'Cerium': '铈',
    'Chlorine': '氯',
    'Chromium': '铬',
    'Cobalt': '钴',
    'Copernicium': '鎶',
    'Copper': '铜',
    'Curium': '锔',
    'Darmstadtium': '鐽',
    'Dubnium': '钅杜',
    'Dysprosium': '镝',
    'Einsteinium': '锿',
    'Erbium': '铒',
    'Europium': '铕',
    'Fermium': '镄',
    'Francium': '钫',
    'Gadolinium': '钆',
    'Gallium': '镓',
    'Germanium': '锗',
    'Gold': '金',
    'Hafnium': '铪',
    'Hassium': '𬭶',
    'Helium': '氦',
    'Holmium': '钬',
    'Indium': '铟',
    'Iodine': 'Iodine',
    'Iridium': '铱',
    'Iron': '铁',
    'Krypton': '氪',
    'Lanthanum': '镧',
    'Lawrencium': '铹',
    'Lead': '铅',
    'Lithium': '锂',
    'Livermorium': '鉝',
    'Lutetium': '镏',
    'Magnesium': '镁',
    'Manganese': '锰',
    'Meitnerium': '䥑',
    'Mendelevium': '钔',
    'Mercury': '汞',
    'Molybdenum': '钼',
    'Moscovium': '镆',
    'Neodymium': '钕',
    'Neon': '氖',
    'Neptunium': '镎',
    'Nickel': '镍',
    'Nihonium': '鉨',
    'Niobium': '铌',
    'Nitrogen': '氮',
    'Nobelium': '锘',
    'Oganesson': '气奥',
    'Osmium': '锇',
    'Oxygen': '氧',
    'Palladium': '钯',
    'Phosphorus': '磷',
    'Platinum': '铂',
    'Plutonium': '钚',
    'Polonium': '钋',
    'Potassium': '钾',
    'Praseodymium': '镨',
    'Promethium': '钷',
    'Protactinium': '镤',
    'Radium': '镭',
    'Radon': '氡',
    'Rhenium': '铼',
    'Rhodium': '铑',
    'Roentgenium': '錀',
    'Rubidium': '铷',
    'Ruthenium': '钌',
    'Rutherfordium': '鈩',
    'Samarium': '钐',
    'Scandium': '钪',
    'Seaborgium': '钅喜',
    'Selenium': '硒',
    'Silicon': '硅',
    'Silver': '银',
    'Sodium': '钠',
    'Strontium': '锶',
    'Sulfur': '硫',
    'Tantalum': '钽',
    'Technetium': '锝',
    'Tellurium': '碲',
    'Tennessine': 'Tennessine',
    'Terbium': '铽',
    'Thallium': '铊',
    'Thorium': '钍',
    'Thulium': '铥',
    'Tin': '锡',
    'Titanium': '钛',
    'Tungsten': '钨',
    'Uranium': '铀',
    'Vanadium': '钒',
    'Xenon': '氙',
    'Ytterbium': '镱',
    'Yttrium': '钇',
    'Zinc': '锌',
    'Zirconium': '锆',

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Synergy (.+): Unlocks synergy ugrades for Tier (.+)$/, '协同 $1: 解锁第 $2 层的协同提升'],
	[/^SlotsSlots: (\d+)\/$/, '插槽：$1\/'],
	[/^Slots: (\d+)\/$/, '插槽：$1\/'],
	[/^(.+) multiplier (.+): Tier (.+) production$/, '$1 加成 $2： 第 $3 层产量'],
	[/^Level: (\d+) Redox bandwidth: Bandwidth available for redoxes$/, '等级：$1 氧化还原带宽：可用于氧化还原的带宽'],
	[/^Level: (\d+) Offline time: Add (\d+) hour to offline gains$/, '等级：$1 离线时间：添加 $2 小时离线收益'],
	[/^Level: (\d+) Redox slots: Number of slots available for redoxes$/, '等级：$1 氧化还原槽：可用于氧化还原的槽数'],
	[/^Level: (\d+) Reaction bandwidth: Bandwidth available for reactions$/, '等级：$1 反应带宽：可用于反应的带宽'],
	[/^Level: (\d+) Reaction slots: Number of slots available for reactions$/, '等级：$1 反应槽：可用于反应的槽数'],
	[/^Boost (\d+): Unlocks boosts for every (\d+) generators$/, '提升 $1：解锁提升每 $2个 发生器'],
	[/^Extra prod (\d+): Unlocks x(\d+) multipliers$/, '额外产品 $1：解锁 x$2 乘数'],
	[/^Ions x(\d+): Ions produce x(\d+) exotic matter$/, '离子 x$1:离子产生 x$2 种外来物质'],
	[/^Isotopes x(\d+): Isotopes produce x(\d+) exotic matter$/, '同位素 x$1:同位素产生 x$2 种外来物质'],
	[/^Molecules x(\d+): Molecules produce x(\d+) exotic matter$/, '分子 x$1:分子产生 x$2 种外来物质'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) \/ (.+) elves$/, '成本：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);